version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  etl_proc_finalhw_airflow:
    image: postgres:13
    container_name: etl_proc_finalhw_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.6.2
    container_name: airflow-webserver
    depends_on:
      etl_proc_finalhw_airflow:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@etl_proc_finalhw_airflow:5432/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@etl_proc_finalhw_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 46BKJoQYlPPOexqtdOhfHy9m2XJktVrGtGxqqZ64Tds=
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow-secret-key
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs  # Используем Docker volume для логов
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow webserver
      "
    networks:
      - my_network

  airflow-scheduler:
    image: apache/airflow:2.6.2
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
      - etl_proc_finalhw_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@etl_proc_finalhw_airflow:5432/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@etl_proc_finalhw_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 46BKJoQYlPPOexqtdOhfHy9m2XJktVrGtGxqqZ64Tds=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs  # Используем Docker volume для логов
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow scheduler
      "
    networks:
      - my_network

  airflow-init:
    image: apache/airflow:2.6.2
    container_name: airflow-init
    depends_on:
      - etl_proc_finalhw_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@etl_proc_finalhw_airflow:5432/airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@etl_proc_finalhw_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 46BKJoQYlPPOexqtdOhfHy9m2XJktVrGtGxqqZ64Tds=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs  # Используем Docker volume для логов
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "
    networks:
      - my_network

volumes:
  mongodb_data:  # Том для данных MongoDB
  postgres_data:  # Том для данных PostgreSQL
  airflow_logs:   # Том для логов Airflow

networks:
  my_network:
    driver: bridge
